version: 5.0.{build}
image: Visual Studio 2017
configuration: Release,Debug
before_build:
- nuget restore
build:
  project: Polymer2RewriteProvider.sln
  verbosity: minimal
artifacts:
- path: bin\Release\Polymer2RewriteProvider5.dll
  name: Es2015-IIS-Rewrite-Provider
