version: 5.0.{build}
skip_tags: true
image: Visual Studio 2017
before_build:
- nuget restore
configuration:
- Release
build:
  project: Polymer2RewriteProvider.sln
  verbosity: minimal
artifacts:
- path: Polymer2RewriteProvider\bin\Release\Polymer2RewriteProvider5.dll
  name: main
- path: Polymer2RewriteProvider\bin\Release\UAParser.dll
  name: main
deploy:
- provider: GitHub
  auth_token:
    secure: 73BMyeWNs+Y0cyNA2FzsPiO4b93zn8pBdSO/oPc9GvT+znZj4vZAWF0bIu0G6G3i
  on:
    branch: master
